In [1]:
print("Hello World")

Hello World

In [3]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python312\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\program files\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.7/9.7 MB 15.3 MB/s eta 0:00:01
   -------- ------------------------------- 2.0/9.7 MB 20.7 MB/s eta 0:00:01
   --------- ------------------------------ 2.3/9.7 MB 18.4 MB/s eta 0:00:01
   ------------------- -------------------- 4.8/9.7 MB 25.7 MB/s eta 0:00:01
   ------------------------ --------------- 6.1/9.7 MB 24.2 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.7 MB 25.7 MB/s eta 0:00:01
   ---------------------------------- ----- 8.5/9.7 MB 24.7 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 25.1 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 24.9 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 22.2 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.3 MB 27.2 MB/s eta 0:00:01
   -------- ------------------------------- 2.7/12.3 MB 34.3 MB/s eta 0:00:01
   ----------- ---------------------------- 3.7/12.3 MB 29.2 MB/s eta 0:00:01
   --------------- ------------------------ 4.8/12.3 MB 30.5 MB/s eta 0:00:01
   ------------------ --------------------- 5.7/12.3 MB 26.3 MB/s eta 0:00:01
   ---------------------- ----------------- 6.9/12.3 MB 25.9 MB/s eta 0:00:01
   -------------------------- ------------- 8.1/12.3 MB 25.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.0/12.3 MB 26.2 MB/s eta 0:00:01
   -------------------------------- ------- 10.1/12.3 MB 26.9 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 25.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 25.2 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 22.6 MB/s eta 0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
   ---------------------------------------- 0.0/349.3 kB ? eta -:--:--
   --------------------------------------- 349.3/349.3 kB 21.2 MB/s eta 0:00:00
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
customers = pd.read_csv("03_Library SystemCustomers.csv")#
books = pd.read_csv("03_Library Systembook.csv")

customers.head()

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
3          NaN             NaN
4          5.0  William Holden

In [6]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [7]:
customers = customers.dropna()

In [8]:
books.dropna()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2 weeks,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2 weeks,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2 weeks,2.0

In [10]:
books = books[books["Customer ID"].isin(customers["Customer ID"])]

In [11]:
display(customers)
display(books)

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2 weeks,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2 weeks,5.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2 weeks,2.0

In [12]:
customers.to_csv("clean_customers.csv", index = False)
books.to_csv("clean_books.csv", index = False)

In [17]:
books["Book checkout"] = books["Book checkout"].str.replace('"','')
books["Book Returned"] = books["Book Returned"].str.replace('"','')

In [19]:
display(customers)
display(books)

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,20/02/2023,25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,24/03/2023,21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,29/03/2023,25/03/2023,2 weeks,3.0
4,5.0,Dune,02/04/2023,25/03/2023,2 weeks,5.0
5,6.0,Little Women,02/04/2023,01/05/2023,2 weeks,1.0
6,7.0,IT,10/04/2063,03/04/2023,2 weeks,6.0
7,8.0,Misery,15/04/2023,03/04/2023,2 weeks,7.0
8,9.0,Catch 22,15/04/2023,16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,20/04/2023,24/04/2023,2 weeks,2.0
10,11.0,1984,23/04/2023,27/04/2023,2 weeks,8.0
11,12.0,Little Women,02/04/2023,01/05/2023,2 weeks,1.0
12,13.0,East of Eden,30/04/2023,05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,01/05/2023,07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,01/05/2023,10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,15/05/2023,01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,32/05/2023,04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,03/06/2023,07/06/2023,2 weeks,5.0
19,20.0,Frankenstein,01/06/2023,20/06/2023,2 weeks,2.0

In [21]:
books["Book checkout"] = pd.to_datetime(books["Book checkout"], dayfirst=True, errors="coerce")
books["Book Returned"] = pd.to_datetime(books["Book Returned"], dayfirst=True, errors="coerce")

In [22]:
books = books.dropna()

In [25]:
books["days Borrowed"] = (books["Book Returned"] - books["Book checkout"]).dt.days

In [26]:
display(books)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,days Borrowed
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0,5
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0,-3
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0,-4
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0,-8
5,6.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0,29
6,7.0,IT,2063-04-10,2023-04-03,2 weeks,6.0,-14617
7,8.0,Misery,2023-04-15,2023-04-03,2 weeks,7.0,-12
8,9.0,Catch 22,2023-04-15,2023-04-16,2 weeks,7.0,1
9,10.0,Animal Farm,2023-04-20,2023-04-24,2 weeks,2.0,4
10,11.0,1984,2023-04-23,2023-04-27,2 weeks,8.0,4
11,12.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0,29
12,13.0,East of Eden,2023-04-30,2023-05-05,2 weeks,2.0,5
13,14.0,America Is in the Heart,2023-05-01,2023-05-07,2 weeks,3.0,6
14,15.0,Wuthering Heights,2023-05-01,2023-05-10,2 weeks,9.0,9
15,16.0,Dark Tales,2023-05-15,2023-06-01,2 weeks,2.0,17
17,18.0,Les Miserables,2023-06-03,2023-06-07,2 weeks,5.0,4
19,20.0,Frankenstein,2023-06-01,2023-06-20,2 weeks,2.0,19